// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhbedvsayaqqsewcilcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoYmVkdnNheWFxcXNld2NpbGNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTQ3MjAsImV4cCI6MjA2NjQzMDcyMH0.nrlGw59XFL9RruekkRRbIHDZyXO8UXgBNiCxwuCSPKk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);